name: BankSystem
main: com.twiistrz.banksystem.BankSystem
author: Twiistrz
version: 1.0-SNAPSHOT
description: A simple banking system.
website: https://github.com/Twiistrz/BankSystem/
softdepend: [Vault]

commands:
    bank:
        description: A simple banking system.
        usage: /<command>