name: BankSystem
main: com.twiistrz.banksystem.BankSystem
author: [Twiistrz, MCPZ Content Team]
version: 1.0-SNAPSHOT
description: A simple banking system.
softdepend: [Vault]

commands:
    bank:
        description: A simple banking system.
        usage: /<command>